<?php
return [
    \Workable\Attribute\Enum\AttributeTypeEnum::TYPE_SALARY => [
        "< 1 triệu",
        "1 - 3 triệu",
        "3 - 5 triệu",
        "5 - 7 triệu",
        "7 - 10 triệu",
        "10 - 12 triệu",
        "12 - 15 triệu",
        "15 - 20 triệu",
        "20 - 25 triệu",
        "25 - 30 triệu",
        "30 - 40 triệu",
        "40 - 50 triệu",
        "Trên 50 triệu",
    ],
    \Workable\Attribute\Enum\AttributeTypeEnum::TYPE_LEVEL => [
        "Nhân viên",
        "Cộng tác viên",
        "Thực tập sinh",
        "Trưởng nhóm",
        "Trưởng phòng",
        "Trưởng dự án",
        "Giám đốc",
        "Phó Giám Đốc",
        "Giám đốc điều hành",
        "Giám đốc chiến lược",
        "Giám đốc nhân sự",
        "Giám đốc kinh doanh",
    ],
    \Workable\Attribute\Enum\AttributeTypeEnum::TYPE_WORK_TYPE => [
        "Toàn thời gian",
        "Bán thời gian",
        "thời vụ",
        "làm từ xa",
    ],
    \Workable\Attribute\Enum\AttributeTypeEnum::TYPE_LITERACY => [
        "Đại học",
        "Cao đẳng",
        "Trung cấp",
        "Cao học",
        "Trung học",
        "Chứng chỉ",
        "Lao động phổ thông",
        "Không yêu cầu",
    ],
    \Workable\Attribute\Enum\AttributeTypeEnum::TYPE_EXP => [
        "Không yêu cầu",
        "6 tháng",
        "1 năm",
        "2 năm",
        "3 năm",
        "4 năm",
        "5 năm",
        "trên 5 năm",
    ],
    \Workable\Attribute\Enum\AttributeTypeEnum::TYPE_LANGUAGE => [
        "Tiếng anh",
        "Tiếng nhật",
        "Tiếng Hàn",
        "Tiếng Trung",
        "Tiếng nga",
        "Tiếng đức",
        "Tiếng tây ban nhà"
    ],
    \Workable\Attribute\Enum\AttributeTypeEnum::TYPE_BENEFIT => [
        "Thưởng",
        "Du lịch",
        "Nghỉ phép",
        "Đào tạo",
        "Khám sức khoẻ",
        "Thư viện",
        "Laptop",
        "Điện thoại",
        "Hoạt động nhóm",
        "Trợ cấp đi lại",
        "Căng teen",
        "THưởng quà",
        "Trông trẻ",
    ],
];



