<?php
return [
    [
        'title'       => 'Super Admin',
        'name'        => 'administrator',
        'description' => 'Nhóm quyền cao nhất',
        'admin_id'    => 1,
        'created_at'  => now(),
        'updated_at'  => now(),
    ],
    [
        'title'       => 'Sale',
        'name'        => 'sale',
        'description' => 'Saler',
        'admin_id'    => 1,
        'created_at'  => now(),
        'updated_at'  => now(),
    ],
    [
        'title'       => 'Author',
        'name'        => 'Editor',
        'description' => 'Đăng bài viết',
        'admin_id'    => 1,
        'created_at'  => now(),
        'updated_at'  => now(),
    ],
    [
        'title'       => 'Cộng Tác Viên',
        'name'        => 'Editor 3',
        'description' => 'Cộng tác viên',
        'admin_id'    => 1,
        'created_at'  => now(),
        'updated_at'  => now(),
    ],
    [
        'title'       => 'Admin',
        'name'        => 'admin',
        'description' => 'Admin',
        'admin_id'    => 1,
        'created_at'  => now(),
        'updated_at'  => now(),
    ],
    [
        'title'       => 'Admin quản lí bài viết',
        'name'        => 'post_admin',
        'description' => 'Admin quản lí bài viết',
        'admin_id'    => 1,
        'created_at'  => now(),
        'updated_at'  => now(),
    ],
    [
        'title'       => 'Cộng tác viên cấp cao',
        'name'        => 'post_master_editor',
        'description' => 'Cộng tác viên cấp cao',
        'admin_id'    => 1,
        'created_at'  => now(),
        'updated_at'  => now(),
    ],
    [
        'title'       => 'Kiểm duyệt bài viết',
        'name'        => 'post_inspector',
        'description' => 'Cộng tác viên kiểm duyệt',
        'admin_id'    => 1,
        'created_at'  => now(),
        'updated_at'  => now(),
    ],
    [
        'title'       => 'Quản lí page',
        'name'        => 'page_manage',
        'description' => 'Quản lí page',
        'admin_id'    => 1,
        'created_at'  => now(),
        'updated_at'  => now(),
    ],
    [
        'title'       => 'QL ứng viên ứng tuyển',
        'name'        => 'apply_cv_manager',
        'description' => 'QL ứng viên ứng tuyển',
        'admin_id'    => 1,
        'created_at'  => now(),
        'updated_at'  => now(),
    ],
    [
        'title'       => 'Dữ liệu mẫu',
        'name'        => 'data_example',
        'description' => 'Dữ liệu mẫu',
        'admin_id'    => 1,
        'created_at'  => now(),
        'updated_at'  => now(),
    ],
];
