<?php
/**
 * Created by PhpStorm.
 * User: dinhhuong
 * Date: 4/22/21
 * Time: 11:00 AM
 */
namespace Workable\Candidate\Enum;

class CareerEnum
{
    const CAREER = [
        1  => 'Bán hàng',
        2  => 'Biên tập/ Báo chí/ Truyền hình',
        3  => 'Bảo hiểm/ Tư vấn bảo hiểm',
        4  => 'Bảo vệ/ An ninh/ Vệ sỹ',
        5  => 'Phiên dịch/ Ngoại ngữ',
        6  => 'Bưu chính',
        7  => 'Chứng khoán - Vàng',
        8  => 'Cơ khí - Chế tạo',
        9  => 'Công chức - Viên chức',
        10 => 'Công nghệ cao',
        11 => 'Công nghiệp',
        12 => 'Dầu khí - Hóa chất',
        13 => 'Dệt may - Da giày',
        14 => 'Dịch vụ',
        15 => 'Du lịch',
        16 => 'Đầu tư',
        17 => 'Điện - Điện tử - Điện lạnh',
        18 => 'Điện tử viễn thông',
        19 => 'Freelance',
        20 => 'Games',
        21 => 'Giáo dục - Đào tạo',
        22 => 'Giao nhận/ Vận chuyển/ Kho bãi',
        23 => 'Hàng gia dụng',
        24 => 'Hàng hải',
        25 => 'Hàng không',
        26 => 'Hành chính - Văn phòng',
        27 => 'Hóa học - Sinh học',
        28 => 'Hoạch định - Dự án',
        29 => 'IT phần cứng/mạng',
        30 => 'IT phần mềm',
        31 => 'In ấn - Xuất bản',
        32 => 'Kế toán - Kiểm toán',
        33 => 'Khách sạn - Nhà hàng',
        34 => 'Kiến trúc - Thiết kế nội thất',
        35 => 'Bất động sản',
        36 => 'Kỹ thuật',
        37 => 'Kỹ thuật ứng dụng',
        38 => 'Làm bán thời gian',
        39 => 'Làm đẹp/ Thể lực/ Spa',
        40 => 'Lao động phổ thông',
        41 => 'Lương cao',
        42 => 'Marketing - PR',
        43 => 'Môi trường',
        44 => 'Mỹ phẩm - Trang sức',
        45 => 'Phi chính phủ/ Phi lợi nhuận',
        46 => 'Ngân hàng/ Tài Chính',
        47 => 'Ngành nghề khác',
        48 => 'Nghệ thuật - Điện ảnh',
        49 => 'Người giúp việc/ Phục vụ/ Tạp vụ',
        50 => 'Nhân sự',
        51 => 'Nhân viên kinh doanh',
        52 => 'Nông - Lâm - Ngư nghiệp',
        53 => 'Ô tô - Xe máy',
        54 => 'Pháp luật/ Pháp lý',
        55 => 'Phát triển thị trường',
        56 => 'Promotion Girl/ Boy (PG-PB)',
        57 => 'QA-QC/ Thẩm định/ Giám định',
        58 => 'Quan hệ đối ngoại',
        59 => 'Quản trị kinh doanh',
        60 => 'Sinh viên làm thêm',
        61 => 'Startup',
        62 => 'Thể dục/ Thể thao',
        63 => 'Thiết kế - Mỹ thuật',
        64 => 'Thiết kế đồ họa - Web',
        65 => 'Thời trang',
        66 => 'Thủ công mỹ nghệ',
        67 => 'Thư ký - Trợ lý',
        68 => 'Thực phẩm - Đồ uống',
        69 => 'Thực tập',
        70 => 'Thương mại điện tử',
        71 => 'Tiếp thị - Quảng cáo',
        72 => 'Tổ chức sự kiện - Quà tặng',
        73 => 'Tư vấn/ Chăm sóc khách hàng',
        74 => 'Vận tải - Lái xe/ Tài xế',
        75 => 'Nhân viên trông quán internet',
        76 => 'Vật tư/Thiết bị/Mua hàng',
        77 => 'Việc làm cấp cao',
        78 => 'Việc làm Tết',
        79 => 'Xây dựng',
        80 => 'Xuất - Nhập khẩu',
        81 => 'Xuất khẩu lao động',
        82 => 'Y tế - Dược',
        83 => 'Trắc Địa / Địa Chất',
        84 => 'Người Nước Ngoài/Việt Kiều',
    ];
}

